name: Issue change labeler

on:
  issues:
    types: [edited, labeled, unlabeled, locked]
  project_card: 
    types: [moved, deleted]

jobs:
  issue-change-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue if changed
        uses: alexcnichols/issue-change-labeler@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changed-label: 'changed'
          qualifying-labels: 'reviewed,endorsed'
