name: Issue change labeler

on:
  issues:
    types: [edited, labeled, unlabeled]
  project_card: 
    types: [moved, deleted]

jobs:
  issue-change-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              if ('${{github.event.action}}' == 'unlabeled' && '${{github.event.label.name}}' == 'help wanted') {
                core.info(`Skipping since the '${{github.event.label.name}}' label was unlabeled.`);
                return;
              } else {
                core.info(`An '${{github.event_name}}.${{github.event.action}}' event action has been triggered.`);
              }
              var issue_number;
              if (context.payload.issue !== undefined) {
                issue_number = context.payload.issue.number;
              } else if (
                context.payload.project_card !== undefined &&
                context.payload.project_card.content_url
              ) {
                issue_number = context.payload.project_card.content_url.split("/").pop();
              } else {
                core.setFailed("Unable to determine issue number.");
                return;
              }
              github.issues.addLabels({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['help wanted']
              });
            } 
            catch (error) {
              core.setFailed(error.message);
            }
      - uses: actions/github-script@v2
        with:
          script: |
            core.debug('second step')
