name: Issue change labeler

on:
  issues:
    types: [edited, labeled, unlabeled]
  project_card: 
    types: [moved, deleted]

jobs:
  issue-change-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        if: ${{ !(context.payload.action == 'unlabeled' && context.payload.label.name == 'help wanted') }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['help wanted']
            })
